// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCgeKSHlWR-l8YLcgvVwjQ_7c6x4QKxs',
    appId: '1:544902525465:web:6cbd9e3723dea05cc87088',
    messagingSenderId: '544902525465',
    projectId: 'app-jeruk',
    authDomain: 'app-jeruk.firebaseapp.com',
    storageBucket: 'app-jeruk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDQ3BuUANepJIW5ZmwksQNhOrFDzfCHQ',
    appId: '1:544902525465:android:f5186dbd43d332c2c87088',
    messagingSenderId: '544902525465',
    projectId: 'app-jeruk',
    storageBucket: 'app-jeruk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCicrXfvAuX3Fag2RbE1tVDrNd4ikI5y80',
    appId: '1:544902525465:ios:37e4eee156475373c87088',
    messagingSenderId: '544902525465',
    projectId: 'app-jeruk',
    storageBucket: 'app-jeruk.firebasestorage.app',
    iosBundleId: 'com.example.appJeruk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCicrXfvAuX3Fag2RbE1tVDrNd4ikI5y80',
    appId: '1:544902525465:ios:37e4eee156475373c87088',
    messagingSenderId: '544902525465',
    projectId: 'app-jeruk',
    storageBucket: 'app-jeruk.firebasestorage.app',
    iosBundleId: 'com.example.appJeruk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUCgeKSHlWR-l8YLcgvVwjQ_7c6x4QKxs',
    appId: '1:544902525465:web:4b463d2b66616076c87088',
    messagingSenderId: '544902525465',
    projectId: 'app-jeruk',
    authDomain: 'app-jeruk.firebaseapp.com',
    storageBucket: 'app-jeruk.firebasestorage.app',
  );

}